name: storarch
description: "A new Flutter project."
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev


version: 1.0.0+1

environment:
  sdk: ^3.5.4


dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  file_picker: ^10.1.9
  permission_handler: ^12.0.0+1
  intl: ^0.20.2
  upgrader: ^11.4.0
  supabase_flutter: ^2.9.1
  uuid: ^4.5.1
  url_launcher: ^6.3.1
  path: ^1.9.1
  app_links: ^6.4.0
  flutter_dotenv: ^5.2.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0


flutter:
  uses-material-design: true

  